on:
  pull_request:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: npm install --legacy-peer-deps

      - name: postinstall
        run: npm run postinstall

      - name: lint
        run: npm run lint:error

      - name: test
        run: npm run test

      - name: build
        run: npm run build
        env:
          DISABLE_ESLINT_PLUGIN: true
